name: 'toy_shop'
version: '1.0.0'
config-version: 2

profile: 'toy_shop'

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]

model-paths:
  - "models"
  - "sources"

models:
  re_data:
    enabled: true

  toy_shop:
    revenue:
      +re_data_monitored: true
      +re_data_time_filter: created_at

      revenue_per_age:
        +re_data_columns:
          - sum
          - age

sources:
  toy_shop:
    toy_shop_sources:
      toy_shop_customers:
        +re_data_monitored: true
        +re_data_time_filter: joined_at
        +re_data_columns:
          - first_name
          - last_name
          - age

seeds:
  toy_shop:
    orders:
      +re_data_monitored: true
      +re_data_time_filter: created_at
      +re_data_metrics:
        table:
          - orders_above_100

        column:
          status:
            - distinct_values

vars:
  re_data:store_table_samples: true
  re_data:anomaly_detector:
    name: modified_z_score
    threshold: 3

  re_data:save_test_history: true

  re_data:owners_config:
    deji:
      - type: slack
        identifier: U02FHBSTW0H
        name: deji
    backend:
      - type: email
        identifier: mateusz@getre.io
        name: mateusz

      - type: email
        identifier: deji@getre.io
        name: deji

      - type: slack
        identifier: U01F80NJW23
        name: mateusz

      - type: slack
        identifier: U02FHBSTW0H
        name: deji  
    frontend:
      - type: slack
        identifier: U02RD3S3WP8
        name: emma

      - type: slack
        identifier: U02FHBSTW0H
        name: deji  

      - type: email
        identifier: deji@getre.io
        name: deji

  re_data:metrics_base:
    table:
      - row_count
      - freshness

    column:
      numeric:
        - min
        - max
        - avg
        - stddev
        - nulls_percent

      text:
        - min_length
        - max_length
        - avg_length
        - missing_percent
